name: FGD Build
on:
  push:
    branches: [ master, dev ]
    paths:
      - 'fgd/**'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'fgd/**'
  workflow_dispatch:
    # Allow triggering manually whenever it's useful.

permissions:
  contents: read
  pull-requests: read

jobs:
  build-fgds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install srctools
        run: python -m pip install -r requirements.txt
      - name: FGD build and folder copy
        run: bash ./build.sh all
      - name: FGD engine dump
        run: python src/hammeraddons/unify_fgd.py exp --engine --binary -o build/fgd.lzma
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: |
            ./build/*.fgd
            ./build/fgd.lzma
          if-no-files-found: error
